# Generated by Django 2.2 on 2023-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20230127_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arhived_at',
            field=models.BooleanField(default=False),
        ),
    ]
