# Generated by Django 4.1.5 on 2023-02-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', '-price']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='arhived_at',
            new_name='archived',
        ),
    ]
